
/*
 * Copyright (c) 2006-2018 RT-Thread Development Team. All rights reserved.
 * License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#include "mbedtls/certs.h"

const char mbedtls_root_certificate[] = 
"-----BEGIN CERTIFICATE-----\r\n"
"MIIGdDCCBNygAwIBAgIQBZydjhHTGkbfCg2/KO28NjANBgkqhkiG9w0BAQsFADBP\r\n"
"MQswCQYDVQQGEwJVUzEYMBYGA1UECgwPU1NMIENvcnBvcmF0aW9uMSYwJAYDVQQD\r\n"
"DB1TU0wuY29tIFRMUyBJc3N1aW5nIFJTQSBDQSBSMTAeFw0yNDEyMDgxMzMzMTNa\r\n"
"Fw0yNjAxMDgxMzMzMTNaMBoxGDAWBgNVBAMMDyoucnQtdGhyZWFkLm9yZzCCASIw\r\n"
"DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMHMSg7PCR5Lm6rIi6NCipd4Op3P\r\n"
"0sK6leFwTU3e8onWHARN6hwR4aTDP7FXXXT9e2GMBjf+BFtDQKC/0O/egDu7tDfX\r\n"
"D9Wcs9D/xyeygh+mr1emtUDnNpd55fbs4yAvrYdjo0GpHAlcJacr9zrOdfIyEjOW\r\n"
"ll9cooysoKEU+wFvyfk1/GyYZ4kxGBmmDlE63KRt5bHhR+8h2wd5R2dAQNkS2Q4R\r\n"
"Filk1IhdFMrIwFA5aK/5T+J499CdmTZ+h/xXKMnzB04LwKoxBySmLyfozzJVwnUO\r\n"
"NUOvoDnxbtKRhtgAydRMRR2Agryp6s31rAusucO6sK4vUSx+g20igNjb+mkCAwEA\r\n"
"AaOCAv8wggL7MAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUebqUd6ANGd005jmk\r\n"
"/Eyl0lpt9YwwagYIKwYBBQUHAQEEXjBcMDgGCCsGAQUFBzAChixodHRwOi8vY2Vy\r\n"
"dC5zc2wuY29tL1NTTC5jb20tVExTLUktUlNBLVIxLmNlcjAgBggrBgEFBQcwAYYU\r\n"
"aHR0cDovL29jc3BzLnNzbC5jb20wKQYDVR0RBCIwIIIPKi5ydC10aHJlYWQub3Jn\r\n"
"gg1ydC10aHJlYWQub3JnMCMGA1UdIAQcMBowCAYGZ4EMAQIBMA4GDCsGAQQBgqkw\r\n"
"AQMBATAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwPQYDVR0fBDYwNDAy\r\n"
"oDCgLoYsaHR0cDovL2NybHMuc3NsLmNvbS9TU0wuY29tLVRMUy1JLVJTQS1SMS5j\r\n"
"cmwwHQYDVR0OBBYEFEueoDz6e84vSGYgj5T5T6hAucOwMA4GA1UdDwEB/wQEAwIF\r\n"
"oDCCAX8GCisGAQQB1nkCBAIEggFvBIIBawFpAHYAGYbUxyiqb/66A294Kk0BkarO\r\n"
"LXIxD67OXXBBLSVMx9QAAAGTpoKPXAAABAMARzBFAiB0sS3wgQo45MsPdq1NGW4S\r\n"
"/RSGvH7AW/p3zrb/ldNjXwIhANccJ7L+nqPpiobVIssXoBKnXkBuRapy+KM8k1V2\r\n"
"TwWHAHcADleUvPOuqT4zGyyZB7P3kN+bwj1xMiXdIaklrGHFTiEAAAGTpoKPZAAA\r\n"
"BAMASDBGAiEA82X+ZwqbyoUQjQCwsTJuifTWOx1FY5qUC9UqesGEfz8CIQD1IX39\r\n"
"BTShIKm/pPtV74he6+8azoNKq749yMn/4aL6MQB2AEmcm2neHXzs/DbezYdkprhb\r\n"
"rwqHgBnRVVL76esp3fjDAAABk6aCj14AAAQDAEcwRQIhAJJ4p5eDv95omZzcQkmU\r\n"
"6WNNG8GEt+bOIUvesVd0jhqeAiAj9vuJs7ISho30U6xePvhTE3Ev3y2nAfTCEzix\r\n"
"QMxtoTANBgkqhkiG9w0BAQsFAAOCAYEAaFQqEairAmVSncX+LuswAK7UP0kQ9Hxx\r\n"
"fbsVsKeo9GtP78tXYbOcG8FHQuD7rFFl2gpkXuknCZ3jt/QCHdfn+M4t0oVkaFZI\r\n"
"NJ0k95PbCvSTH27G21L1/tjytS4jPCjmkmNuyo3/BfGwruOJ/vCTrmM2P+7har2J\r\n"
"d1+3LSNmnFHtkLDEPRv3+spX17ujgURUdrApLn4j6TrzhleC7YRzGjjapEK4B3gP\r\n"
"2bECXQrM+nB5WkYwwTfQLsolBiWHJVtXGZYL2wFs/7aJKeIKlsSkFHHRTbEf5Y86\r\n"
"BVVYmttDIuyeBhNzusyptHN8XsMpk84qy0rONN6Dl+s29pCwL4YNKce2XnsmpHOS\r\n"
"bQWJ4MYRWznx4EWFlrOIJxGXM4yGSe8Mupllxeh4thHxErYYNPaN4ZjWhsHcfg+1\r\n"
"oU6WNBY9RreqVxPNf1KH+yFH5Tg0nVVNzlJtB76cr24cQd6FA1oxQrp7rPZUDhTs\r\n"
"HjHkiA5aEWXf3NDo8s8wzZKhpFreXZz1\r\n"
"-----END CERTIFICATE-----\r\n"
"-----BEGIN CERTIFICATE-----\r\n"
"MIIE/jCCA+agAwIBAgIRAMT4RcgnYpHswrPdHceMh00wDQYJKoZIhvcNAQELBQAw\r\n"
"ezELMAkGA1UEBhMCR0IxGzAZBgNVBAgMEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G\r\n"
"A1UEBwwHU2FsZm9yZDEaMBgGA1UECgwRQ29tb2RvIENBIExpbWl0ZWQxITAfBgNV\r\n"
"BAMMGEFBQSBDZXJ0aWZpY2F0ZSBTZXJ2aWNlczAeFw0yNDA2MjEwMDAwMDBaFw0y\r\n"
"ODEyMzEyMzU5NTlaME8xCzAJBgNVBAYTAlVTMRgwFgYDVQQKDA9TU0wgQ29ycG9y\r\n"
"YXRpb24xJjAkBgNVBAMMHVNTTC5jb20gVExTIElzc3VpbmcgUlNBIENBIFIxMIIB\r\n"
"ojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEArBsCFEDaO9kp5LVy+Q61qs0c\r\n"
"eyTudkfMpnOW86WVgjxn1Ol3GVEEJeGnAJacW6Me3/DElI3p/oAiH+RozfSaV1xq\r\n"
"zXYaFLr5xwzP3DjUiV8ez41QLh14JZLR+WV6VcNfYY0X1BtmvgmbjhICpycy/9DR\r\n"
"ibURLan6zcuisqA89B/2vVYnQG+ACJh4mTi7kWggWT5/vVII/U1kxUxH3b3F9KK/\r\n"
"LxZxmhcNZbeqU655LLUB/WqmAcfneAg41ZDWiE2qCS2xvByaNZZmUvkWdlWWUxp9\r\n"
"vFoOQ3TcqZVscwVTHL/s4btRCiJakhrrx516K9ohURYwctW1XYu7EflaLuD1GsPx\r\n"
"EB+Ly0WBxzNq1L/2eah3Iw8Xxfglx63oxEtD2mGgPxCybn0nDfyMYpGiDkVrgSFK\r\n"
"69+KXC4/mxU5cq+QlhhWyRSXlrM+QkBcUdySWtZpM3xx2YhNSWYKI82i2Mysc7R9\r\n"
"iG4rz5zJjJVIS7biFu4dSTRjXgQ/W+6RnfiFz84bAgMBAAGjggEnMIIBIzAfBgNV\r\n"
"HSMEGDAWgBSgEQojPpbxB+zirynvgqV/0DCktDAdBgNVHQ4EFgQUebqUd6ANGd00\r\n"
"5jmk/Eyl0lpt9YwwDgYDVR0PAQH/BAQDAgGGMBIGA1UdEwEB/wQIMAYBAf8CAQAw\r\n"
"HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMCMGA1UdIAQcMBowCAYGZ4EM\r\n"
"AQIBMA4GDCsGAQQBgqkwAQMBATBDBgNVHR8EPDA6MDigNqA0hjJodHRwOi8vY3Js\r\n"
"LmNvbW9kb2NhLmNvbS9BQUFDZXJ0aWZpY2F0ZVNlcnZpY2VzLmNybDA0BggrBgEF\r\n"
"BQcBAQQoMCYwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmNvbW9kb2NhLmNvbTAN\r\n"
"BgkqhkiG9w0BAQsFAAOCAQEAFTEjMQzlG8JU3bIPbc+vWUtusUzRXSoVmY7Y4Ybx\r\n"
"phiK7+coZgU0MOHYdSjmSGp16wly0l0L3acKwBanu5WqUnaeXyPqkgUOOD6w0JHc\r\n"
"FBcLXCCqPD7hnhYAjQuaU8t50OCEkCEYK4R5nh75paChmYPFci0XJRCFQHOK7xCo\r\n"
"boWSRjszDM/0/YYu/GV0fMAPxbMvKbr7WrCgGHsCl96mhPoRvUH8+cP4wLkoN81V\r\n"
"mv+BjERE6JwxadQFa9pxLacnCBNA7KfGteVkI2xN1MbiuATZujRQ7MxEBv+aZ7Sb\r\n"
"LZwAQqijFKgzcvRBeETD8JmmeKO7Ksf/XkPOvOA99wK5dQ==\r\n"
"-----END CERTIFICATE-----\r\n"
"-----BEGIN CERTIFICATE-----\r\n"
"MIIEMjCCAxqgAwIBAgIBATANBgkqhkiG9w0BAQUFADB7MQswCQYDVQQGEwJHQjEb\r\n"
"MBkGA1UECAwSR3JlYXRlciBNYW5jaGVzdGVyMRAwDgYDVQQHDAdTYWxmb3JkMRow\r\n"
"GAYDVQQKDBFDb21vZG8gQ0EgTGltaXRlZDEhMB8GA1UEAwwYQUFBIENlcnRpZmlj\r\n"
"YXRlIFNlcnZpY2VzMB4XDTA0MDEwMTAwMDAwMFoXDTI4MTIzMTIzNTk1OVowezEL\r\n"
"MAkGA1UEBhMCR0IxGzAZBgNVBAgMEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UE\r\n"
"BwwHU2FsZm9yZDEaMBgGA1UECgwRQ29tb2RvIENBIExpbWl0ZWQxITAfBgNVBAMM\r\n"
"GEFBQSBDZXJ0aWZpY2F0ZSBTZXJ2aWNlczCCASIwDQYJKoZIhvcNAQEBBQADggEP\r\n"
"ADCCAQoCggEBAL5AnfRu4ep2hxxNRUSOvkbIgwadwSr+GB+O5AL686tdUIoWMQua\r\n"
"BtDFcCLNSS1UY8y2bmhGC1Pqy0wkwLxyTurxFa70VJoSCsN6sjNg4tqJVfMiWPPe\r\n"
"3M/vg4aijJRPn2jymJBGhCfHdr/jzDUsi14HZGWCwEiwqJH5YZ92IFCokcdmtet4\r\n"
"YgNW8IoaE+oxox6gmf049vYnMlhvB/VruPsUK6+3qszWY19zjNoFmag4qMsXeDZR\r\n"
"rOme9Hg6jc8P2ULimAyrL58OAd7vn5lJ8S3frHRNG5i1R8XlKdH5kBjHYpy+g8cm\r\n"
"ez6KJcfA3Z3mNWgQIJ2P2N7Sw4ScDV7oL8kCAwEAAaOBwDCBvTAdBgNVHQ4EFgQU\r\n"
"oBEKIz6W8Qfs4q8p74Klf9AwpLQwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQF\r\n"
"MAMBAf8wewYDVR0fBHQwcjA4oDagNIYyaHR0cDovL2NybC5jb21vZG9jYS5jb20v\r\n"
"QUFBQ2VydGlmaWNhdGVTZXJ2aWNlcy5jcmwwNqA0oDKGMGh0dHA6Ly9jcmwuY29t\r\n"
"b2RvLm5ldC9BQUFDZXJ0aWZpY2F0ZVNlcnZpY2VzLmNybDANBgkqhkiG9w0BAQUF\r\n"
"AAOCAQEACFb8AvCb6P+k+tZ7xkSAzk/ExfYAWMymtrwUSWgEdujm7l3sAg9g1o1Q\r\n"
"GE8mTgHj5rCl7r+8dFRBv/38ErjHT1r0iWAFf2C3BUrz9vHCv8S5dIa2LX1rzNLz\r\n"
"Rt0vxuBqw8M0Ayx9lt1awg6nCpnBBYurDC/zXDrPbDdVCYfeU0BsWO/8tqtlbgT2\r\n"
"G9w84FoVxp7Z8VlIMCFlA2zs6SFz7JsDoeA3raAVGI/6ugLOpyypEBMs1OUIJqsi\r\n"
"l2D4kF501KKaU73yqWjgom7C12yxow+ev+to51byrvLjKzg6CYG1a4XXvi3tPxq3\r\n"
"smPi9WIsgtRqAEFQ8TmDn5XpNpaYbg==\r\n"
"-----END CERTIFICATE-----"
;

const size_t mbedtls_root_certificate_len = sizeof(mbedtls_root_certificate);

